[package]
name = "proto"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.11"
prost-types = "0.11"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tonic = "0.9.1"
[build-dependencies]
tonic-build = "0.9.2"